### ISSUE TITLE
Unable to get prometheus Data From Grafana

### ISSUE THREAD

**Issue by nabbdl** [openshift/cluster-monitoring-operator#100]
I'm unable to get any data from Grafana. I have deployed the manifest files for promtheus operator and grafana from your repository. However it seems that the prometheus datasource created on grafana does not allow to connect on prometheus which is protected by an oauth-proxy.

**Comment by brancz** [comment]
The manifests in `assets/` are not meant to be applied against your cluster directly, the cluster-monitoring-operator does that for you and manages the entire lifecycle. Keep in mind that this is only targeting OpenShift 3.11 at the moment.
