### ISSUE TITLE
Race condition updating grafana ClusterRoleBinding

### ISSUE THREAD

**Issue by 2uasimojo** [openshift/cluster-monitoring-operator#1024]
SRE-P primary on call has been paged with a few events whose symptoms include the following log from cmo:

```
E1216 22:13:13.459284       1 operator.go:274] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating Grafana failed: reconciling Grafana ClusterRoleBinding failed: updating ClusterRoleBinding object failed: clusterrolebindings.rbac.authorization.k8s.io "grafana" already exists
```

The operator mostly hits [this error](https://github.com/openshift/cluster-monitoring-operator/blob/201f93976a8a35b8f495585abb8265b3f26c21f2/pkg/client/client.go#L1126-L1127) because [this condition](https://github.com/openshift/cluster-monitoring-operator/blob/201f93976a8a35b8f495585abb8265b3f26c21f2/pkg/client/client.go#L1113-L1116) doesn't short-circuit the function, which we believe is because [RHACM is laying down a conflicting resource](https://issues.redhat.com/browse/OHSS-2298).

When it does hit this code path, it fails frequently. This is likely because the [Delete](https://github.com/openshift/cluster-monitoring-operator/blob/201f93976a8a35b8f495585abb8265b3f26c21f2/pkg/client/client.go#L1121) is asynchronous, and the object still exists when the [Create](https://github.com/openshift/cluster-monitoring-operator/blob/201f93976a8a35b8f495585abb8265b3f26c21f2/pkg/client/client.go#L1126) is attempted immediately thereafter.

Arguably the reconcile could be more idempotent, deleting the CRB and then requeueing so the Create is handled in a subsequent iteration. But that doesn't really gel with the pattern of the surrounding code.

The alternative is probably to use Update instead of Delete+Create -- which _does_ gel with the pattern of the other functions in the neigborhood.

(Please don't add a poll after the `Delete` to wait until the resource is gone.)

**Comment by lilic** [comment]
Hey @2uasimojo! Thanks for the issue but do you mind instead to open a bugzilla for this, we track all our bug reports via bugzilla, thanks!

**Comment by 2uasimojo** [comment]
Sure thing: https://bugzilla.redhat.com/show_bug.cgi?id=1913398
