### ISSUE TITLE
Send alert to external AlertManager

### ISSUE THREAD

**Issue by tomleb** [openshift/cluster-monitoring-operator#1043]
Hi,

would it be possible to support adding external AlertManagers in the alertmanagers list in the prometheus configuration?

Maybe the AlertManager resource can have a field `externalAlertManager` or something.

I think this feature is a must to be able to centralize the monitoring of multiple clusters.

What do you think?

**Comment by lilic** [comment]
Hello 👋 Thank you for your request, but feature requests tend to go via customer support, so if you contact them they will create proper RFE issue in our backlog. Best would be to describe why you need this and we can figure out the solution together. Thank you!

**Comment by tomleb** [comment]
Hi,

will try to go through OpenShift customer support.

Thank you!

**Comment by simonpasquier** [comment]
/close

This is being tracked as an RFE
