### ISSUE TITLE
Create a new Grafana data source

### ISSUE THREAD

**Issue by danielmenezesbr** [openshift/cluster-monitoring-operator#1045]
How do I create a new Grafana data source from Openshift Monitoring?

In my case, I would like to create a new Grafana data source from Openshift Monitoring to avoid having two instances of Grafana (one in OpenShift Service Mesh and other in OpenShift Monitoring). It is possible?

**Comment by lilic** [comment]
Hey 👋 The grafana that is deployed with the stack is read only so you cannot add a new data source, as it's meant to be the platform grafana not a user workload grafana, so it's not possible. Best option like you said is to have another instance yes into the user monitoring instance.
