### ISSUE TITLE
How to add new Prometheus Alert rules to prometheus running in openshift-monitoring namespace

### ISSUE THREAD

**Issue by SAbdulRahuman** [openshift/cluster-monitoring-operator#1049]
Hi 
We are using Openshift cluster 4.6.8 and we have required to add new rules to prometheus, which is running in openshift-monitoring namespace.

Can we add new rules to prometheus, if yes could you share some details.

Note:
 We have `clusteradmin` privilege for our Openshift cluster.

**Comment by simonpasquier** [comment]
:wave: modifying the rules shipped by the cluster monitoring operator isn't supported. If you want to deploy your own alerts, have a look at user workload monitoring.

**Comment by simonpasquier** [comment]
/close

as stated in the [docs](https://docs.openshift.com/container-platform/4.6/monitoring/configuring-the-monitoring-stack.html#support-considerations_configuring-the-monitoring-stack), it isn't supported.
