### ISSUE TITLE
Is it possible to configure namespaces in scope of interaction for Prometheus operator?

### ISSUE THREAD

**Issue by kkujawa-sumo** [openshift/cluster-monitoring-operator#1260]
Is it possible to configure [namespaces](https://github.com/prometheus-operator/prometheus-operator/blob/f0ddd0a0caf5099fcf2bbe61a9ae9e78a1121259/cmd/operator/main.go#L191) in scope of interaction for Prometheus operator which is managed by Cluster Monitoring Operator?

Is there any option to change namespaces in scope of interaction for Prometheus Operator which is by default available on OpenShift 4.6?

**Comment by fpetkovski** [comment]
If the prometheus operator is managed by Cluster Monitoring Operator, it is not possible to change the `namespaces` flag.

**Comment by kkujawa-sumo** [comment]
@fpetkovski Thank you!

**Comment by fpetkovski** [comment]
Adding to that, If you want to monitor custom namespaces, you should try to see if use workload monitoring fits your use case: https://docs.openshift.com/container-platform/4.6/monitoring/enabling-monitoring-for-user-defined-projects.html
