### ISSUE TITLE
Reconfigure default setup of Cluster Monitoring Operator

### ISSUE THREAD

**Issue by domino7** [openshift/cluster-monitoring-operator#128]
Is it possible to reconfigure default setup of Cluster Monitoring Operator? How to disable resetting setup to default state?
Documentation is a little bit misleading in this, I already described details here: https://github.com/openshift/openshift-docs/issues/12500

> Example: I would like to install Cluster Monitoring Operator with OpenShift-Ansible, turn off resetting mechanism and patch configuration (e.g. ServiceMonitorSelector, ServiceMonitorNamespaceSelector) as additional, post-installation tasks to provide applications monitoring in scope of Openshift-Monitoring stack with Ansible playbook.

Any documentation describing customised setups, or any other correct way of providing applications monitoring with the usage of openshift-monitoring playbook will be greatly appreciated as well.

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
