### ISSUE TITLE
Heketi / GlusterFS metrics in Prometheus

### ISSUE THREAD

**Issue by Rikbruggink** [openshift/cluster-monitoring-operator#134]
Hi!,

We are in the progress to migrating our clusters to the 3.11 release and we are wondering if it is possible to enable the Heketi / GlusterFS metrics in the Prometheus set-up? We tried the annotate method as mentioned in a blog article on the Red Hat Storage blog[1] but this is not working

[1] https://redhatstorage.redhat.com/2018/09/14/improved-volume-management-for-red-hat-openshift-container-storage-3-10/

**Comment by squat** [comment]
@Rikbruggink the Prometheus Operator, which this Cluster Monitoring Operator leverages, is not configured to support that annotation format. Instead, the Prometheus Operator provides an object known as a ServiceMonitor, which can be used exactly for the purpose of defining a service target for scraping. Here are some docs explaining how to use service monitors [0] as well as exampels [1].

[0] https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources
[1] https://github.com/coreos/prometheus-operator/blob/master/example/user-guides/getting-started/example-app-service-monitor.yaml

**Comment by squat** [comment]
xref: https://github.com/coreos/prometheus-operator/issues/1547#issuecomment-401092041

**Comment by Rikbruggink** [comment]
@squat thanks for the pointer in the right direction, the servicemonitor works now. Closing this issue.
