### ISSUE TITLE
alertmanager-main secret is overwritten instantly after edit

### ISSUE THREAD

**Issue by yasharne** [openshift/cluster-monitoring-operator#1352]
Hi
We are using openshift `4.7.5` and based on the docs [here](https://docs.openshift.com/container-platform/4.7/monitoring/managing-alerts.html#applying-custom-alertmanager-configuration_managing-alerts) I should be able to change alert manager's config by editing the `alertmanager-main` secret, but when I change the secret and apply it (both through the UI and `oc` command) the secret's content get overridden instantly to the original content

**Comment by simonpasquier** [comment]
the procedure described in the documentation should work. Feel free to open a support request to Red Hat.

/close
