### ISSUE TITLE
node-exporter "--collector.mountstats" was removed. Why¿?

### ISSUE THREAD

**Issue by hmarrao** [openshift/cluster-monitoring-operator#1376]
Hello I'm currently working for IBM/kyndryl and we rely on openshift-monitoring to provide services to our customers.

We have noticed that `--collector.mountstats` was removed from the project stream.

We rely on node-exporter to perform the file storage device monitoring and without this feature, node-exporter doesn't generate the proper information.

Please let us know if `--collector.mountstats` was removed intentionally or is an errata:

- commit removing definition: https://github.com/openshift/cluster-monitoring-operator/commit/13844917277521a726d7f3b0f81abae5c2b60808#diff-d3e4bd88987d4d4c4a89e8c92babec1a9435adc5834a98d1bf12076b399fdf62

This is mainly to understand if we can still rely on openshift monitoring for this metric or we should start thinking of other ways to obtain these kinds of metrics.

Thank you all,

**Comment by hmarrao** [comment]
Ok found this regarding the mountstats:

- https://github.com/openshift/cluster-monitoring-operator/commit/ecc4c250bef2d196aaeda4ed70e52951eaee6cf4

It seems that this was a user requested feature that was removed.

**Comment by hmarrao** [comment]
@simonpasquier can you confirm that feature isn't going to be re-added and that collectors aren't configurable from cluster-monitoring config.yaml file¿?

**Comment by simonpasquier** [comment]
I confirm that we're not going to enable the collector back.
