### ISSUE TITLE
Metric 'kube_namespace_labels' no longer showing namespace labels

### ISSUE THREAD

**Issue by daskanu** [openshift/cluster-monitoring-operator#1415]
Hey guys,

we previously updated one of our gorgeous OpenShift clusters to 4.8 and immediately realised that several of our monitoring dashboards which are relying on the metric 'kube_namespace_labels' stopped working because the namespace labels are missing.

The problem is that you decided to hardcode the parameter
```bash
--metric-labels-allowlist=pods=[*],nodes=[*]
```
in your [kube-state-metrics deployment asset (Line 37)](https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/kube-state-metrics/deployment.yaml) which disables the namespace labels in 'kube_namespace_labels'.

In my opinion a good Kubernetes operator should offer configuration parameters for such things and not rely on hardcoded values.

Is there any chance that you make such things configurable through the operator's configmap?

Thanks in advance.

**Comment by jomeier** [comment]
Same here.

**Comment by simonpasquier** [comment]
this has been fixed down to OCP 4.8.
