### ISSUE TITLE
Roles in Grafana

### ISSUE THREAD

**Issue by henry-zektser-vineti** [openshift/cluster-monitoring-operator#148]
By default, it seems even a user with `cluster-admin` is not an admin in Grafana, and can not set up things like Alerting. In digging around, it seems there's no way to grant users these roles. Is this intentional or am I perhaps missing a setting somewhere in the operator?

**Comment by nyirimark** [comment]
Any solution for this?
How grant a cluster-admin to grafana admin?, or create new user for grafana admin / editor

**Comment by metalmatze** [comment]
The stack shipped by the cluster-monitoring-operator is immutable and so is Grafana.

**Comment by paulfantom** [comment]
Modifications to grafana instance are out of scope for this project. If you need any changes, you need to ship your own grafana instance.

/close
