### ISSUE TITLE
OSX mapfile command not found

### ISSUE THREAD

**Issue by xiaoxi1989** [openshift/cluster-monitoring-operator#149]
./hack/build-jsonnet.sh
+ set -o pipefail
+ prefix=assets
+ rm -rf assets
+ mkdir assets
+ rm -rf tmp
+ mkdir tmp
+ jsonnet -J jsonnet/vendor jsonnet/main.jsonnet
+ mapfile -t files
++ jq -r 'keys[]' tmp/main.json
./hack/build-jsonnet.sh: line 16: mapfile: command not found

how it build in mac ox ?

**Comment by jmcshane** [comment]
I ran into the same problem and resolved it by updating my path to ensure that the homebrew installed bash 5.0.2 was earlier in the `$PATH` than the macos default version of bash. Here's an article I found describing some of the considerations around this: https://scriptingosx.com/2019/02/install-bash-5-on-macos/
