### ISSUE TITLE
How to get pod labels or annontations using servicemonitor?

### ISSUE THREAD

**Issue by danilorsilva** [openshift/cluster-monitoring-operator#160]
I have a Prometheus Operator working fine and scrape service label using `targetLabels`. I would like to know, how can i get labels or annotations from my pods.

Thanks

**Comment by danilorsilva** [comment]
I am using `podTagetLabels` without success.

**Comment by metalmatze** [comment]
I am not sure I fully understand, but can you search in the generated configuration (which you can find in the Prometheus UI on `/config`) for `__meta_kubernetes_pod_label_` and see if something shows up? If so the `podTargetLabels` have been picked up.

**Comment by metalmatze** [comment]
This issue is a duplicate of https://github.com/coreos/prometheus-operator/issues/2147
Closing here as the coreos/prometheus-operator is better suited for this questions.
