### ISSUE TITLE
Configure grafana for user workload monitoring

### ISSUE THREAD

**Issue by adarshaj** [openshift/cluster-monitoring-operator#1618]
I could not find documentation about connecting user deployed grafana with openshift user workload monitoring. An example included in this project would be great.

**Comment by ibotty** [comment]
Still relevant IMO.

**Comment by Tsimon-Dorakh** [comment]
If I understood the topic correctly until Openshift 4.10 it was possible to reuse the same integration configuration (endpoint, credentials) as internal Grafana used. But [Grafana was removed](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-monitoring-grafana-component-removed) in Openshift 4.11 and the integration stopped working.

As an alternative it's still possible to integrate with Openshift Prometeus using priviliged service account token providing it as a Bearer header. Example:
```
curl -X GET -kI "https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091/api/v1/targets" -H "Authorization: Bearer ey...Bg"
```

But I'm not sure whether it's something we could rely on and this option will not be removed in the future. Maybe somebody from RedHat team may clarify this?
