### ISSUE TITLE
Readme clarification 

### ISSUE THREAD

**Issue by nabbdl** [openshift/cluster-monitoring-operator#166]
In the readme file it is stated that : 
Users interested in leveraging Prometheus for application monitoring on OpenShift should consider using OLM to easily deploy a Prometheus Operator and setup new Prometheus instances to monitor and alert on their applications.
This sounds a bit confusing. Does it mean that in order to monitor application we have to create a new instance of Prometheus with the help of the « Prometheus Operator » provided by the « OpenShift cluster monitoring operator ». Or do we have to install a stand-alone « Prometheus operator » ?
If we can use Prometheus operator from cluster monitoring operator for application monitoring does it have to be in the same project (openshift-monitoring) or do we have to provision the app-prometheus in same namespace of the application ?

**Comment by aditya-konarde** [comment]
It is recommended that you do not make any changes to the cluster-monitoring-operator, or the prometheus managed by it. 

What you can do is create a new prometheus operator in a separate namespace using OLM, and via that, deploy a new prometheus instance configured to watch your applications. You can also create an alertmanager via your prometheus operator for alerts.

**Comment by s-urbaniak** [comment]
as @aditya-konarde correctly stated cluster monitoring operator is not meant to be used for application monitoring and the suggested installation of a dedicated prometheus operator via OLM is spot on :ok_hand: If you don't mind I'll close this issue.
