### ISSUE TITLE
{Request} Ability to configure Prometheus Exporters

### ISSUE THREAD

**Issue by saintdle** [openshift/cluster-monitoring-operator#1708]
In the doc's, it basically says you cannot alter the OOTB cluster monitoring provided instance of Prometheus.
You have the ability to provide a user-workload instance of prometheus. But this looks to give limited access to some components

We are using a product called VMware vRealize Operations, which is focused on virtualisation monitoring. But we have expanded this further, included a kubernetes monitoring component, focused on full relationship mapping from virtual layer to the K8s VMs and the k8s resources.

As it stands today, it looks like we cannot use the prometheus instance in the OCP cluster, as we'd need to edit it to provide exporters.

I've details a setup here for a non OCP cluster for you to review, to see how we achieve this today > https://veducate.co.uk/vrops-kubernetes-prometheus-telegraf/

**Comment by danielm0hr** [comment]
I've looked at the blog post you linked and also at the [vRealize Operations docs](https://docs.vmware.com/en/VMware-vRealize-Operations-Management-Pack-for-Kubernetes/1.6/kubernetes-solution/GUID-218C1F64-9CF7-4982-8064-A74AD35F9675.html) but I've not found _how_ this is actually accessing Prometheus. Is it using Prometheus' federation endpoint? Or is it directly accessing /metrics endpoints of the exporters? Maybe you could provide some more information about the architecture.

That said, what we currently offer as a supported integration point for external observability services is [Prometheus remote_write](https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#configuring_remote_write_storage_configuring-the-monitoring-stack).
