### ISSUE TITLE
Allow -skip-auth-regex to be customized

### ISSUE THREAD

**Issue by jmcshane** [openshift/cluster-monitoring-operator#179]
In our environment, we scrape the data from each prometheus server running inside an OpenShift cluster and federate to an external data store. This is done using prometheus federation.

In my use case, i want to change skip auth regex to `^/(metrics|federate)`

In this operator, I would like to be able to customize the -skip-auth-regex in the configmap file. Is this something that would be supported by this operator? Would you be open to a PR to resolve this?

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
