### ISSUE TITLE
crio metrics via http is not safe

### ISSUE THREAD

**Issue by lance5890** [openshift/cluster-monitoring-operator#1918]
1. I have send email to secalert@redhat.com , but the crio metrics is exposed in cmo
2. When I  use ocp 4.9 release, I found the crio metrics are exposed by http:x.x.x.x:9537，and any one can get the metrcis without tls cert
3. I found this was caused by the cluster-monitoring-operator config, such as follows(which not use tls cert communicate with crio):

<img width="437" alt="image" src="https://user-images.githubusercontent.com/30207518/225535224-1bf9493b-c1b8-4646-b8c5-a14edaac50bc.png">

4. and the vulnerabilities show as follows

<img width="606" alt="image" src="https://user-images.githubusercontent.com/30207518/225535346-94d953b2-4896-4a77-b372-19571f6915fd.png">

**Comment by lance5890** [comment]
@jan--f @simonpasquier

**Comment by jan--f** [comment]
@lance5890 can you list steps how to reproduce this? 4.9 is no longer supported so we'd need to check newer verions.

**Comment by lance5890** [comment]
> 2\. 9537

we can see metrics via  http://${VIP_ADDRESS}:9537/metrics  by browser
