### ISSUE TITLE
Reject invalid PrometheusRule objects beforehand rather than failing the reconciliation

### ISSUE THREAD

**Issue by sastorsl** [openshift/cluster-monitoring-operator#1928]
Referencing #prometheus-operator/prometheus-operator/issues/5191 and #prometheus-operator/prometheus-operator/pull/5221

As pr the referenced issue, written by @simonpasquier

**What is missing?**

When the Thanos/Prometheus controllers detect an invalid PrometheusRule object (invalid PromQL expression for instance), they fail the reconciliation (and for Prometheus, the Reconciled condition will be set to False). Instead the controllers should reject the invalid object and proceed (just like we do for service/pod monitors and probes).

**Why do we need it?**

In self-service environments, blocking the reconciliation means that one single user can block all other users if they push a bad rule.

**Comment by slashpai** [comment]
This change is included in `0.64` version of prometheus-operator. The PR to update in fork is here https://github.com/openshift/prometheus-operator/pull/223

**Comment by slashpai** [comment]
https://github.com/openshift/prometheus-operator/pull/233 is the updated PR. Once https://github.com/openshift/cluster-monitoring-operator/pull/1961 merged PO PR can be merged

**Comment by slashpai** [comment]
/close
This is fixed
