### ISSUE TITLE
typo in 4.14 CHANGELOG.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by juzhao** [openshift/cluster-monitoring-operator#1992]
checked 4.14 CHANGELOG.md
https://github.com/openshift/cluster-monitoring-operator/blob/release-4.14/CHANGELOG.md

typo see below

> - [#1950](https://github.com/openshift/cluster-monitoring-operator/pull/1950) Disable CORS headers on Thanos querier by defaut and add a flag to enable them back.

`defaut` should be `default`

> - [#1291](https://github.com/openshift/cluster-monitoring-operator/pull/1291) Drop high caredinality cAdvisor metrics via [kube-prometheus #1250](https://github.com/prometheus-operator/kube-prometheus/pull/1250)

`caredinality` should be `cardinality`

> - [#894](https://github.com/openshift/cluster-monitoring-operator/pull/894) Bump jsonnet depdencies:
> - kubernetes-mixin: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/475: alerts: adjust error message accrodingly to recent change

  `depdencies` should be `dependencies`, `accrodingly` should be `accordingly`

- [#898](https://github.com/openshift/cluster-monitoring-operator/pull/898) Bump jsonnet depdencies for kube-mixin:

  `depdencies` should be `dependencies`

**Comment by juzhao** [comment]
also for CONTRIBUTING.md
https://github.com/openshift/cluster-monitoring-operator/blob/release-4.14/CONTRIBUTING.md

> You should keep this in mind when decding in which release you want your feature or fix.
`decding` should be `deciding`

> - unit tests, can be run seperately by `make test-unit`.
- Prometheus rule tests, can be run seperately by `make test-rules`.
- end to end tests, can be run seperately by `make test-e2e`.
`seperately` should be `separately`

> So we can use the following commnad to run the test function 
`commnad` should be `command`

**Comment by marioferh** [comment]
Done here:
https://github.com/openshift/cluster-monitoring-operator/pull/1993

**Comment by juzhao** [comment]
it seems we need to file bug to jira then it can add  jira/valid-bug label, close this issue, and tracked in
https://issues.redhat.com/browse/OCPBUGS-14816
