### ISSUE TITLE
Additional Scrape Configuration is not supported

### ISSUE THREAD

**Issue by IvanovOleg** [openshift/cluster-monitoring-operator#2175]
Hello,
I would like to use kubecost with a prometheus created by the cluster-monitoring-operator. I created a connection between them, but the problem is that kubecost wants some additional scrape configurations to be set in the prometheus. I didn't find that field in the list of the supported fields in the documentation. I tried to add that field manually to the prometheus resource and it worked for 5 minutes till the next reconcile execution. Is there a plan to introduce that field or a way to disable reconcile for a specific prometheus instance or all of them?

**Comment by a-thorat** [comment]
@IvanovOleg 
You can configure additional scrape spec config under prometheus cr names k8s using secret key value.
  
additionalScrapeConfigs:
    key: opa-exporter-config.yaml
    name: opa-exporter
    optional: true

secret could be like this
opa-exporter-config.yaml
job_name: opa-exporter
kubernetes_sd_configs:
- role: service

Additionally you can refer this page https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

**Comment by a-thorat** [comment]
@IvanovOleg  i am sure you might have explored ServiceMonitor CR as well for metrics scraping with service? Not sure this will help but just trying a lil bit

**Comment by IvanovOleg** [comment]
@a-thorat Yes, SM was my backup plan.

**Comment by mahmut-Abi** [comment]
/open can i open this, same issue
