### ISSUE TITLE
How to change default servicemonitors interval

### ISSUE THREAD

**Issue by yasharne** [openshift/cluster-monitoring-operator#2176]
Hi
As the number of nodes on the openshift cluster increased, our Prometheus instances could not handle the amount of load, so I wanted to decrease the interval of service monitors, I tried to increase the interval of `node-exporter`'s service monitor, but as it is managed by the operator, it will get reverted to the default value. 
Is it possible to change the interval?

**Comment by a-thorat** [comment]
@yasharne 
I was able to change it under node-exporter ServiceMonitor and not got override as well.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 1.6.1
    monitoring.openshift.io/collection-profile: full
  name: node-exporter
  namespace: openshift-monitoring
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 20s

Also note 
interval 
string
Interval at which metrics should be scraped If not specified Prometheus' global scrape interval is used.

Have you tried to change it CR Prometheus-k8s in opneshift-monitoring? 
scrapeInterval 
string
Interval between consecutive scrapes. 
 Default: "30s"

Please let me know if this works for you.
