### ISSUE TITLE
node-exporter can't be configured to tolerate a taint

### ISSUE THREAD

**Issue by benhwebster** [openshift/cluster-monitoring-operator#227]
CMO deployed on OpenShift 3.11:

I have some dedicated nodes that I have tainted for certain pods, but there is no way to add a toleration for the node-exporter (that I can find at least) and the pods are now miss-scheduled on the tainted nodes, and I assume would not be placed back on the nodes should they be deleted, and I'm guessing the operator would revert any changes I make to the daemonset.

**Comment by metalmatze** [comment]
Yes, exactly. The operator will reconcile every few seconds and override those changes. What would you like to change for the taint to be recognized?

**Comment by benhwebster** [comment]
I was thinking you would just add it to the cluster-monitoring-config under the node-exporter section, similar to the node selector sections, except for tolerations, or ignore taints altogether for the node-exporter if thats somehow easily achievable (and won't cause problems).

**Comment by thepax** [comment]
I believe node-exporter has to tolerate any taints:

    tolerations:
      - operator: "Exists"

**Comment by padyx** [comment]
Just ran into this issue with tainted nodes as well: These will not have the `node-exporter` pod scheduled on them and thus no metric of them is available...

Is there any workaround that you know of?

**Comment by padyx** [comment]
Seems like this is fixed in master and release-3.11 branch roughly three weeks ago (file: [daemonset.yaml](https://github.com/openshift/cluster-monitoring-operator/blob/release-3.11/assets/node-exporter/daemonset.yaml) ) : fe4ef560d6d32f692f0afed0ba5d4fdab7153028 and 3b4ebe6ebbdcddaa5d9fc80f4cb026819a08460c

However, the last release on quay.io seems to be 9 months old.
Is there a possibility of creating a new release of this and pushing it to Quay?

**Comment by paulfantom** [comment]
CMO image on quay.io is updated after each merge to master. At the time of writing this image with tag `latest` was updated 3 hours ago. 

Source: https://quay.io/repository/openshift/origin-cluster-monitoring-operator?tab=tags

**Comment by paulfantom** [comment]
Closing as this is already fixed on master branch.

**Comment by padyx** [comment]
@paulfantom Is the 3.11 Image not being updated from the release-3.11 branch?
The labels for the quay.io Image for 3.11 points to the commit 10e4317d15025bfcdf3337d2bbde0b745c510d00 which is from February this year.

**Comment by paulfantom** [comment]
@padyx Yes, that's a bug and we are working on a solution.
