### ISSUE TITLE
Dead Man's Snitch documentation needs work

### ISSUE THREAD

**Issue by gswallow** [openshift/cluster-monitoring-operator#234]
The documentation on how to connect Prometheus to a Dead Man's Snitch, with and without Pagerduty, is incomplete:

https://github.com/openshift/cluster-monitoring-operator/blob/9c97908591f4b4fc3b12251c4b6ab0d6289fdbc0/Documentation/user-guides/configuring-prometheus-alertmanager.md

What it should do is mention that you need to set up a generic webhook receiver, direct deadmansswitch alerts to that, and create an integration from Dead Man's Snitch to PagerDuty.  Instead, they indicate that you should fire all events to PagerDuty directly.

Maybe I'm wrong, though.

**Comment by s-urbaniak** [comment]
it seems we have a nice blog post for this, closing.
