### ISSUE TITLE
Improvement for Alert KubeletTooManyPods?

### ISSUE THREAD

**Issue by ulikl** [openshift/cluster-monitoring-operator#284]
Currently a fix value of 250 is used for the maximum number of pods per node.
But Kubernetes allows to set it per node.

This alert rule could be made a bit more cluster specific via :
```
max (kubelet_running_pod_count{job="kubelet"}) by (instance)   < on () group_left() max(kube_node_status_capacity_pods{job="kube-state-metrics"}) * 0.9
```
where kube_node_status_capacity_pods is the number of allowed pods per node from job kube-state-metrics.
Note: the value of kube_node_status_capacity_pods is typically lower for master and infra nodes.

This rule unfortunately cannot be defined on the exact limit per node as the label "node" from the "kube-state-metrics" is not available for metrics from other jobs.
I only found that the node IP and node name can be matched by using relabel_configs from kubernetes_sd_configs with role "node" for kubelet.
Then the node label can be added from the node label  "__meta_kubernetes_node_name". The node IP can be extracted from label "__address__" or label "instance".

Kind Regards, 
 Ulrike

**Comment by metalmatze** [comment]
Hey @ulikl.
Thanks for raising the issue. The original rule is from another project: https://github.com/kubernetes-monitoring/kubernetes-mixin

I'm not entirely sure why we did not go with `kube_node_status_capacity_pods` but looking at it right now, it seems good to me.
Would you mind creating another Issue or PR over at the other repository?
Feel free to `/cc @metalmatze` there in the description.

Here is the line that would need to be changed:
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/9069b2c1be0ce32f63f9a01c4a4f8d69bc4e37d5/alerts/system_alerts.libsonnet#L70

**Comment by ulikl** [comment]
I opened the Issue  https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/223 there.

There will only be an improvement for Kubernetes 1.14 and higher.
