### ISSUE TITLE
Customizing container args

### ISSUE THREAD

**Issue by rezie** [openshift/cluster-monitoring-operator#292]
Is there currently an easier way to add custom arguments to the monitoring stack's components? For example, I'm currently using `oc patch` as a hacky workaround to add the `-request-logging=true` argument to the oauth-proxy container, but if there are multiple arguments to update, across multiple containers,  that quickly becomes difficult to manage. In addition, due to the reconciliation process, I'm not sure how I can modify other fields that aren't directly exposed (e.g. `replicas`). It looks like some configuration options are available (https://github.com/openshift/cluster-monitoring-operator/blob/master/Documentation/user-guides/configuring-cluster-monitoring.md#reference), but unfortunately that isn't sufficient for my use case.

**Comment by s-urbaniak** [comment]
@rezie the cluster monitoring operator is meant to be running as an "immutable" component inside OpenShift. Except the options in the referenced configmap there is currently no possibility to configure `--request-logging` of the proxy sidecar.

In addition, as you mentioned, these changes would be reconciled away pretty soon by the operator.

Let us know if you have additional questions, closing this issue until then :-)

**Comment by rezie** [comment]
@s-urbaniak Thanks for the reply. I think enabling request-logging is a rather important configuration setting especially in an enterprise setting (which is probably a common deployment environment for OpenShift). Has there been any consideration to modify the default set of args, at the very least?
