### ISSUE TITLE
Update CMO to newer release

### ISSUE THREAD

**Issue by Drakkai** [openshift/cluster-monitoring-operator#293]
Because of company policy I need to run kube-rbac-proxy container in node-exporter with stronger ciphers suite. As the CMO is immutable we are not able to add args in node-exporter daemonset but I saw that newer release (3.11) has already these ciphers in args
`--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256`

My question, is there any options to update CMO to release-3.11?

**Comment by brianotte** [comment]
The mechanism that seems to be the only option to secure kube-rbac-proxy to use TLS 1.2 -- (i.e. prevent TLS 1.0 and TLS1.1):

Disable the cluster-monitoring-operator in openshift-monitoring project by scaling down the pod:

oc scale deployment cluster-monitoring-operator --replicas=0 -n openshift-monitoring

Edit the node-exporter daemonset in openshift-monitoring project and add:  - '--tls-min-version=VersionTLS12' to the end of the args for the kube-rbac-proxy section -- just above the image for kube-rbac-proxy:

- args:
- '--secure-listen-address=:9100'
- '--upstream=http://127.0.0.1:9101/'
- '--tls-cert-file=/etc/tls/private/tls.crt'
- '--tls-private-key-file=/etc/tls/private/tls.key'
- '--tls-min-version=VersionTLS12'

Once saved, the node-exporter pod will recycle and will only connect with TLS 1.2

NOTE: Must keep cluster-monitoring-operator scaled to 0

Is there no better mechanism for Openshift 3.11 deployments to modify this security issue?  This seems BAD.

**Comment by s-urbaniak** [comment]
Unfortunately we don't bump to newer versions of CMO in 3.11. Having said that tls 1.2 min version is used already in 4.x.

**Comment by s-urbaniak** [comment]
Closing out as this refers to 3.11. Please open a bugzilla ticket or contact support if need further help in 3.11.

**Comment by Drakkai** [comment]
@brianotte thanks for reply, we've managed to resolve this last year.
