### ISSUE TITLE
how to change kube-rbac-proxy version for node-exporter

### ISSUE THREAD

**Issue by sreekanth-ragi** [openshift/cluster-monitoring-operator#294]
Hello Team,

We would like to know how to change the version for kube-rbac-proxy used by the node-exporter daemonset, as the current 0.3.1 version with OSO 3.11 allows SSLv3 and Tlsv1. kube-rbac-proxy 0.4.1 seems to have the fix for it. I tried changing the version in DaemonSet but it reverts back to older version.

Thanks,
Sreekanth

**Comment by Drakkai** [comment]
You have to turn off cluster-monitoring-operator then you will be able to change the version in daemonset.

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
