### ISSUE TITLE
Update Kubelet label to use GA label

### ISSUE THREAD

**Issue by rphillips** [openshift/cluster-monitoring-operator#371]
I took a stab at this in https://github.com/openshift/cluster-monitoring-operator/pull/370 but it looks like the generator is producing the old label (`beta.kubernetes.io/os: linux`). The new label should be used `kubernetes.io/os: linux`.

ref: https://jira.coreos.com/browse/POD-114

**Comment by rphillips** [comment]
@paulfantom could you take this on? I am not sure how the jsonnet code changes.

**Comment by s-urbaniak** [comment]
Closing out as things have been merged elsewhere.
