### ISSUE TITLE
Condition and polling period to detect "reconciling Prometheus object"

### ISSUE THREAD

**Issue by bysnupy** [openshift/cluster-monitoring-operator#403]
* Version: OCP v3.11

* Background

I modified `cluster-monitoring-config` and restarted prometheus pods to take effect changes. Even though restart pods, sometimes cluster operator make the pods restart again. 
It's inconsistent behavior, such as, sometime restart the pods, sometimes not, and sometimes restart again immediately, sometimes not...

I can verified the following log messages from cluster operator pod logs, when pods restart.
~~~
operator.go:155] ConfigMap updated: openshift-monitoring/cluster-monitoring-config
...
prometheus.go:269] reconciling Prometheus object
prometheus.go:275] waiting for Prometheus object changes
~~~

It seems periodical polling detect different resource version of configmap and other objects and make pods restart to sync. This issue can occur by polling time and update time.

* Issue
Do we have a solution to prevent useless restart by operator after changes ? 
It make someone  misunderstand as a runtime problem.
And what is trigger to occur "reconciling Prometheus object" except updating configmap and how often does it poll to detect the changes ?

I wonder if we can control this behavior.

* Reproducing steps

You might repeat again between 1 and 3 steps until reproducing issues.

1. Modify "cluster-monitoring-config" to change "retention" to "30d".
~~~
# oc edit cm cluster-monitoring-config -n openshift-monitoring
...
    prometheusK8s:
      baseImage: registry.redhat.io/openshift3/prometheus
      retention: 30d
...
~~~

2. Restart prometheus-k8s pods
~~~
# oc delete prometheus-k8s-0 prometheus-k8s-1
OR
# oc scale --replicas=0 sts/prometheus-k8s -n openshift-monitoring
# oc scale --replicas=2 sts/prometheus-k8s -n openshift-monitoring
~~~

3. Watch the pods 
~~~
# watch -n 1 oc get pod -n openshift-monitoring
~~~

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
