### ISSUE TITLE
Metric openshift cores usage > cluster cores usage

### ISSUE THREAD

**Issue by fabianofranz** [openshift/cluster-monitoring-operator#413]
The `openshift:cpu_usage_cores:sum` metric reports the total CPU usage by OpenShift infra components, however the amount returned there is currently *higher* than the `cluster:cpu_usage_cores:sum` (total CPU usage in the cluster) metric.

The example below comes from the *production* Prometheus cache:

- total CPU of *28*
- used cluster CPU of *~1.747*
- used OpenShift CPU of *~2.027*

```
sum without (label_beta_kubernetes_io_instance_type, label_node_role_kubernetes_io) (cluster:capacity_cpu_cores:sum{_id="REDACTED"}) = 28

cluster:cpu_usage_cores:sum{_id="REDACTED"} = 1.7470000000088475

openshift:cpu_usage_cores:sum{_id="REDACTED"} = 2.0268118829672432
```

Either the total or the OpenShift CPU amount is wrong.

**Comment by fabianofranz** [comment]
@squat @smarterclayton @brancz incorrect CPU usage metric here, PTAL.

**Comment by fabianofranz** [comment]
Let me know if you need cluster IDs where this happens, but really we confirmed the issue in the great majority of the clusters checked.

**Comment by fabianofranz** [comment]
fyi @cben

**Comment by smarterclayton** [comment]
I suspect the recording rule is double counting pods and containers.  Also, the recording rule isn't correctly accounting for crio kubelet overhead, or kernel overhead.  I am working with Fabiano and the PM team to narrow down what we actually need

**Comment by LiliC** [comment]
@smarterclayton Could it be a similar issue as https://github.com/openshift/cluster-monitoring-operator/pull/153

**Comment by smarterclayton** [comment]
For containers, we only want container_name="" (since there is CPU usage that doesn't belong to containers that is in the parent cgroup).

**Comment by smarterclayton** [comment]
We're missing the stuff covered by system services which is non-trivial

**Comment by smarterclayton** [comment]
#425 fixes this by identify workload CPU/mem and subtracting it from total CPU/mem, while also filtering for only pod cgroup accounting (not double counting).  This ensures infra measures host CPU (kernel, Kubelet, crio) as well.

**Comment by s-urbaniak** [comment]
Seems to be fixed, closing.
