### ISSUE TITLE
misleading cluster monitoring message re: Cronjobs

### ISSUE THREAD

**Issue by shalberd** [openshift/cluster-monitoring-operator#470]
https://github.com/openshift/cluster-monitoring-operator/blob/df5f1b80ef3c6fb6d083051182a659bba92e9619/assets/prometheus-k8s/rules.yaml#L693

The message to KubrCronJobRunning "cronjob is taking more than 1h to complete is misleading.
As Brian Brazil, one of Prometheus' founders, points out, CronJob monotoring has nothing to do with next schedule time, more with last completion time and errors occurring.

https://stackoverflow.com/questions/47343842/is-there-a-way-to-monitor-kube-cron-jobs-using-prometheus

Can someone please either change that check or alter the description?

Thanks a lot

**Comment by brancz** [comment]
This alert is coming from one of our dependencies: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/6a0450b32a0f3b25299dcca7f40157e21c50d023/alerts/apps_alerts.libsonnet#L159-L171

Please report this there. If you want you can also submit a PR to fix it here :slightly_smiling_face: .

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
