### ISSUE TITLE
code-of-conduct may need some improvements

### ISSUE THREAD

**Issue by lucab** [openshift/cluster-monitoring-operator#471]
I've been asking around for existing of Code-of-Conduct (CoC) covering OpenShift components, and I've been pointed at the one in this repository as an example to follow.
Unfortunately, I do believe this one may benefit from some improvements before actually being useful.

In particular:
 * it is missing any contact details
 * it is missing a designed person to mediate issues
 * it is unclear what "cluster-monitoring-operator events" actually covers
 * the statement "cluster-monitoring-operator reserves the right ..." seems to imply this repo can make its own judgement
 * it reads like a quick sed-replace of the [CoreOS one](https://github.com/coreos/ignition/blob/master/code-of-conduct.md)

**Comment by LiliC** [comment]
@lucab we are happy to change it, if we apply the above, will it be enough? What if we just do same as k8s org has in place? 

Thanks for this! :)

**Comment by lucab** [comment]
There seem to be some internal OpenShift-wide ongoing discussions on how to have a single umbrella CoC, to be referenced by all components.
I don't see a single clear outcome at this point, but I'd suggest to keep this on hold for the moment and then try to jump on that train.

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
