### ISSUE TITLE
prometheus-k8s pods need readiness/liveliness probe

### ISSUE THREAD

**Issue by krisachai** [openshift/cluster-monitoring-operator#493]
We have a openshift 3.11 cluster running and we're seeing our prometheus return 500 response due to unknown reason. This makes our monitoring flapping all the time as the culprit pod doesn't get kill.

It would be nice if we could have a health check built into https://github.com/openshift/cluster-monitoring-operator/blob/release-3.11/assets/prometheus-k8s/prometheus.yaml. 

This could be a simple cmd like
`curl -x "" localhost:9090/-/ready` 
`curl -x "" localhost:9090/-/healthy`

Thank you.

**Comment by simonpasquier** [comment]
The Prometheus operator now configures `readinessProbe` and `livenessProbe` for Prometheus with the latest version.

cc @s-urbaniak, this can be closed.
