### ISSUE TITLE
Openshift_cluster_monitoring_operator : Wait for the ServiceMonitor CRD to be created

### ISSUE THREAD

**Issue by dibhoussam** [openshift/cluster-monitoring-operator#495]
Please, I'm deploying Openshift Cluster, with one master two nodes and one infra node.
When I launch the deployment playbook _**playbooks/deploy_cluster.yml**_
in output I receive this problem
<img width="1263" alt="Screenshot 2019-10-03 at 11 22 05" src="https://user-images.githubusercontent.com/40125413/66119158-0e74ba80-e5d0-11e9-9016-4762657e1f47.png">
<img width="1211" alt="Screenshot 2019-10-03 at 11 22 40" src="https://user-images.githubusercontent.com/40125413/66119206-23e9e480-e5d0-11e9-9a89-ce9567fbd5ce.png">

**Comment by paulfantom** [comment]
Please open a bugzilla ticket if this is still a problem.

/close
