### ISSUE TITLE
How can I use AlertManager for my apps running in a different namespace?

### ISSUE THREAD

**Issue by a2chitta** [openshift/cluster-monitoring-operator#535]
All the default rules in prometheus are checking for the namespaces: 
namespace=~"(openshift.*|kube.*|default|logging)
How can I include my custom namespace to this list, so that I can use these rules in alertmanager for my application/pods.

**Comment by sichvoge** [comment]
This is currently not a supported feature. 

We are currently working on extending our ability to also monitor your apps, and not just the infra services we own in OpenShift. That also comes with the ability to define alerting rules for your apps. You will see a first milestone of that functionality in the next upcoming months.

**Comment by simonpasquier** [comment]
FYI this effort is tracked here: https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/user-workload-monitoring.md

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
