### ISSUE TITLE
alertmanager-main secret is being overwritten

### ISSUE THREAD

**Issue by shasbomm** [openshift/cluster-monitoring-operator#536]
I am performing the following steps to add slack integration 

1. kubectl -n openshift-monitoring get secret alertmanager-main -ojson | jq -r '.data["alertmanager.yaml"]' | base64 -D > alertmanager.yaml

2. kubectl delete secret alertmanager-main  -n openshift-monitoring

3. Edit the alertmanager.yaml and added the slack configuration.
global:
  resolve_timeout: 5m
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
  - match:
      alertname: DeadMansSwitch
    repeat_interval: 5m
    receiver: deadmansswitch
receivers:
- name: default
  slack_configs:
  - api_url: https://hooks.slack.com/services/xxx/xxx/xxx
    channel: slack-channel
- name: deadmansswitch

4. Once edited, apply the configuration:
kubectl -n openshift-monitoring create secret generic alertmanager-main --from-literal=alertmanager.yaml="$(< alertmanager.yaml)" --dry-run -oyaml | kubectl -n openshift-monitoring replace secret --filename=-

I see alerts only for short duration on slack channel  as alertmanager-main secret file is being overwritten by the operator. Can you please let me know the next steps.

**Comment by LiliC** [comment]
@shasbomm Hello 👋 Which version are you using? Double checked with openshift release 4.1.x, works as intended, the configuration is applied correctly for us and it even after upgrade stays.

> Can you please let me know the next steps.

If you have openshift support, you can just go through the support channel and provide them more information for them to help you debug. :)

**Comment by paulfantom** [comment]
FYI `DeadMansSwitch` alert was replaced in OpenShift 4.x with `Watchdog` alert. 

Full procedure is described in our docs at https://docs.openshift.com/container-platform/4.1/monitoring/cluster-monitoring/configuring-the-monitoring-stack.html#configuring-alertmanager

**Comment by shasbomm** [comment]
Thanks for the response. The issue had been root caused. This secret currently had the addonmanager.kubernetes.io/mode: Reconcile label applied which caused changes to be overridden. We needed to adjust the label value to be EnsureExists.
