### ISSUE TITLE
Add a "too many cluster LIST calls" alert

### ISSUE THREAD

**Issue by smarterclayton** [openshift/cluster-monitoring-operator#54]
A common naive integration pattern is to LIST all of a type of resource (especially CRDs), process them, and then sleep in a loop.  This works for low cardinality resources but eventually could bring down an API server.

https://bugzilla.redhat.com/show_bug.cgi?id=1609862 is an example of a case.  Prow has an inefficient LIST poller (will be switched to informer soon).  As number of resources grew, the CPU use grew until it caused the server to crash out.  Symptoms were CPU saturation (which we have an alert for), but root cause is rate of resources listed.

We should consider alerting when the rate of objects or bytes returned by a list call reaches a threshold proportional to the use of the cluster.  I would suggest doing it per resource - if `rate LIST per resource * number of objects in resource (or bytes of response as a proxy) > threshold`.

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
