### ISSUE TITLE
TelemeterClientDown alert when telemetry is disabled by a missing pull-secret entry

### ISSUE THREAD

**Issue by vrutkovs** [openshift/cluster-monitoring-operator#550]
Version: 4.3.0-0.okd-2019-11-12-230620

In OKD-on-FCOS pull-secret may be deployed without a token for telemetry. In this case the operator doesn't start telemetry deployment.

However all standard alerts are deployed - after some time TelemeterClientDown alert is firing

**Comment by sgreene570** [comment]
@vrutkovs  By pull-request do you mean pull-secret?

**Comment by vrutkovs** [comment]
@sgreene570 ah, good catch, renamed for clarity

**Comment by s-urbaniak** [comment]
@vrutkovs thanks a lot, that's a good catch. Let's continue pursuing this in BZ.

**Comment by s-urbaniak** [comment]
filed https://bugzilla.redhat.com/show_bug.cgi?id=1775524

**Comment by lilic** [comment]
@vrutkovs hey follow up question, is this an alert that continues firing even after some time, or just temporary?

**Comment by vrutkovs** [comment]
TelemeterClientDown alerts doesn't seem to be installed any more in OKD 4.4
