### ISSUE TITLE
Adding http_proxy to grafana

### ISSUE THREAD

**Issue by Mihai-CMM** [openshift/cluster-monitoring-operator#555]
Any way to set http_proxy env vars in grafana deployment on openshift 3.11
Please let me know how to use the operator behind enterprise proxies

The oc set env workaround is always beaten by the operator
https://github.com/openshift/openshift-ansible/issues/11137

Thanks

**Comment by s-urbaniak** [comment]
@Mihai-CMM http proxy settings are being inherited from the installer. If you configured OpenShift installer to use a global proxy, those settings should be inherited.

**Comment by Mihai-CMM** [comment]
Thank you Sergiusz but that is not actually true due to the above openshift/openshift-ansible#11137 issue, I do understand that it is maybe not in the scope of current project but it does mean that i cannot use cluster-monitoring-operator behind an enterprise proxy without an workaround here

**Comment by s-urbaniak** [comment]
@Mihai-CMM oh, excuse, my bad, I overlooked you are using OpenShift 3.11. HTTP Proxy support was added to OpenShift 4.x

**Comment by Mihai-CMM** [comment]
@s-urbaniak can you suggest an workaround?long shoot i know But i need to ask before giving up on this cool feature we want to use :)
