### ISSUE TITLE
grafana-proxy doesn't get http proxy informations

### ISSUE THREAD

**Issue by glupu** [openshift/cluster-monitoring-operator#565]
Hello,

I'm running 3.11.154 and I'm having some troubles with openshift monitoring: when I try to access grafana, I received a 504 Gateway Time-out error and in the grafana-proxy logs:

2019/11/25 09:55:14 oauthproxy.go:649: error redeeming code (client:172.20.2.1:59894): Post https://public_hostname:443/oauth/token:  dial tcp x.x.x.x:443: connect: connection timed out
2019/11/25 09:55:14 oauthproxy.go:439: ErrorPage 500 Internal Error Internal Error

Clearly, grafana-proxy doesn't get the http proxy settings that were correctly defined cluster wide and successfully used by other components, like cluster console, kibana within logging etc.

Can you please advise on how can I make grafana-proxy get the http proxy details?

Thanks,
George

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
