### ISSUE TITLE
oc 3.10 / Mac OS X, prometheus-operator won't come up

### ISSUE THREAD

**Issue by cunningt** [openshift/cluster-monitoring-operator#57]
I'm trying to get the cluster-monitoring-operator working on openshift 3.10 - I'm on Mac OS X and I'm using 

lilguylaptop:~ cunningt$ ~/bin/v3.10/oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.10.0+7eee6f8-2
kubernetes v1.10.0+b81c8f8

When I use scripts/deploy-on-openshift.sh to install the cluster-monitoring-operator, it looks like the cluster-monitoring-operator comes up okay, but the prometheus-operator does not : 

lilguylaptop:~ cunningt$ ~/bin/v3.10/oc get pods
NAME                                          READY     STATUS             RESTARTS   AGE
cluster-monitoring-operator-5c7cb9d65-vbqwv   1/1       Running            0          10m
prometheus-operator-558f555f45-d6wj4          0/1       CrashLoopBackOff   6          10m

Attached is the log for the prometheus-operator.  

[prometheus-operator-558f555f45-d6wj4.log](https://github.com/openshift/cluster-monitoring-operator/files/2271461/prometheus-operator-558f555f45-d6wj4.log)

**Comment by cunningt** [comment]
Script seems to work okay in minishift w/oc 3.9.0, so maybe it is something with oc 3.10 or a non-minishift environment on Mac OS X?

**Comment by cunningt** [comment]
I see this failure as well on minishift 1.22 with oc 3.10.0.

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
