### ISSUE TITLE
Two prometheus operators on the same cluster

### ISSUE THREAD

**Issue by punkprzemo** [openshift/cluster-monitoring-operator#571]
Hello, README says that for application monitoring we should deploy custom `prometheus-operator`
So i have already in my openshift (v3.11) cluster `cluster-monitoring-operator` for cluster monitoring.
Later I have deployed `prometheus-operator` in custom project for application monitoring.
It appears that two prometheus operatos in the same cluster  are conflicting. After the deployment of the `prometheus-operator` for apps it took over the control of the prometheus and alermanagers for cluster monitoring which brake those pods ( statefullsets are modified so prometheus and alertmanagers pods in openshift-monitoring project won't start anymore) 
Is it possible to use openshift `cluster-monitoring-operator` and custom `prometheus-operator` for apps on the same openshift cluster? Could you please advice some configuration modifications to avoid those conflicts?

Regards
Przemek Mika

**Comment by paulfantom** [comment]
Yes, it is possible. For that you need to deploy your custom `prometheus-operator` and use `namespaceSelector` to exclude namespaces which are watched by `prometheus-operator` deployed via `cluster-monitoring-operator`. Those namespaces are listed in https://github.com/openshift/cluster-monitoring-operator/blob/release-3.11/jsonnet/main.jsonnet#L76.

**Comment by punkprzemo** [comment]
Hi Paweł,

Thanks for answer. I'm still confused where exactly should I set this `namespaceSelector`. It should be set somewhere in configuration of `prometheus-operator` (i'm talking here about https://github.com/coreos/prometheus-operator) ?

**Comment by paulfantom** [comment]
Yes, `namespaceSelector` is a field in Prometheus CR. 

We also added `--deny-namespaces` in https://github.com/coreos/prometheus-operator/pull/2710 which would probably more important to you as you need to exclude some namespaces from your custom prometheus-operator installation. This option is passed to `prometheus-operator` binary, an example can be found at https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/prometheus-operator-user-workload/deployment.yaml#L29

---
FYI in OpenShift 4.3 we are releasing tech preview of User Workload Monitoring which might do what you are doing by yourself and solve your problems wich custom prometheus-operator.

**Comment by punkprzemo** [comment]
Last answer helped me a lot. I can confirm that `--deny-namespaces` solved  my issue.
Thank you very much.
