### ISSUE TITLE
Duplicate RBAC rules in cluster-monitoring-operator-role.yaml

### ISSUE THREAD

**Issue by chancez** [openshift/cluster-monitoring-operator#59]
I'm guessing something is up with the manifest generation, but there are duplicate RBAC rules in https://github.com/openshift/cluster-monitoring-operator/blob/9a3ff15b5784580f11c9fe04e077e2524da2dc56/manifests/cluster-monitoring-operator-role.yaml#L40:15

**Comment by squat** [comment]
Yes we are aware of this. It’s due to the lazy script that combines them https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/merge_cluster_roles.py. The fix is simple and I plan on getting to it shortly tm

**Comment by squat** [comment]
Fixed in #60
