### ISSUE TITLE
Ensure rslave mount propagation in node-exporter

### ISSUE THREAD

**Issue by brancz** [openshift/cluster-monitoring-operator#6]
Kubernetes [has reverted `HostToContainer` as the default mount propagation strategy](https://github.com/kubernetes/kubernetes/pull/62462), we now need to make sure we explicitly use this strategy in the node-exporter, otherwise filesystem metrics will be off.

/cc @derekwaynecarr @ironcladlou @elad661 @mxinden

**Comment by s-urbaniak** [comment]
this is fixed in #71, closing
