### ISSUE TITLE
edit grafan secrets

### ISSUE THREAD

**Issue by matancarmeli7** [openshift/cluster-monitoring-operator#609]
Hi! I am trying to add new elasticsearch datasource to the grafana pod that this operator creates.
By default my user doesn't have permissions to do it, so i tried to edit the grafana-config secret and changed the admin user to my user and it worked but after the pod is running the secret is going back to its initial state. I also tried to add it in the grafana-datasources secret but when i enter the grafana datasources and test it, the error 400 always shows up. If there is any way that i can edit the grafan-cofig secret and that it wont change back i would love to hear about it.

Thanks

**Comment by LiliC** [comment]
@matancarmeli7 Hello, yes the cluster-monitoring-operator will sync the changes, we don't support the edits and on purpose don't allow user to have those permissions. You can try to run another instance of grafana in your user namespaces to achieve that. Hope that answers your question?

**Comment by matancarmeli7** [comment]
I prefer using the existing operator. I know that there is a way to add datasource to grafana-datasources secret. I did it and it added the datasource but when i tested it it wrote immediately error 400. I added elasticsearch datasource with certificates and ca. someone did it and can send a correct file of the datasource?

**Comment by paulfantom** [comment]
cluster-monitoring stack provides immutable, read-only grafana instance. Any modifications to it are out of scope for the project.

/close
