### ISSUE TITLE
Where to find documentation for some of the metrics

### ISSUE THREAD

**Issue by pranithk** [openshift/cluster-monitoring-operator#672]
Could you let me know what the following metrics mean? I was not able to find documentation for these in https://github.com/openshift/cluster-monitoring-operator/blob/master/Documentation/data-collection.md so wondering if they are yet to be documented or they are documented somewhere else. Please point me to the location if they are already documented.

cluster:usage:containers:sum
cluster:usage:pods:terminal:workload:sum
cluster:usage:resources:sum
kube_pod_status_ready:etcd:sum
kube_pod_status_ready:image_registry:sum
name_reason:cluster_operator_degraded:count
name_reason:cluster_operator_unavailable:count

**Comment by lilic** [comment]
@pranithk they are all recording rules you can search through this file and see what metrics are used for example for `cluster:usage:containers:sum ` -> https://github.com/openshift/cluster-monitoring-operator/blob/3dcc0ce32ad1237674cdf09fa7b14b7efcbe8a29/assets/prometheus-k8s/rules.yaml#L380-L381

Why are you interested in those specifically?

**Comment by paulfantom** [comment]
Closing due to staleness.

/close
