### ISSUE TITLE
Node CPU stats are not accurate

### ISSUE THREAD

**Issue by mcginne** [openshift/cluster-monitoring-operator#693]
I have noticed on an Openshift Cluster using k8s-prometheus-adapter that often I see significant differences between the CPU % reported by `kubectl top nodes` and those reported by logging onto the host and running `top` or by the following query in prometheus:
`100 - (avg by (hostname) (irate(node_cpu_seconds_total{mode="idle"}[10m])) * 100)`

e.g:
```
kubectl top nodes
NAME             CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
10.143.130.157   2898m        74%    2755Mi          20%       
10.143.130.164   2960m        75%    2614Mi          19%       
10.143.130.213   2109m        53%    2674Mi          20%       
10.143.130.228   435m         11%    2165Mi          16%       
10.143.130.231   1315m        33%    2038Mi          15%
```
Output from top on `10.143.130.157`:
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/27362732/76203927-5a670380-61ef-11ea-98cf-e7ef615a2dd8.png">

It looks like the query being used in Openshift 4 is `nodeQuery: sum(1 - rate(node_cpu_seconds_total{mode="idle"}[5m]) * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{<<.LabelMatchers>>}) by (<<.GroupBy>>)` -> https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/prometheus-adapter/config-map.yaml#L7

But this does not seem to be accurate.

When looking at node CPU I really care about if the node is close to being maxed out - and currently the results from k8s-prometheus-adapter are not accurate, as I see them regularly reporting ~70% busy - whereas in fact the node is running close to 100%.

I also checked this out on Kube clusters using heapster & metrics-server and both of those are giving fairly accurate values for `kubectl top nodes` - so this issue seems specific to k8s-prometheus-adapter

**Comment by lilic** [comment]
Thanks for your issue. What version of openshift cluster are you using?  The lines you are referencing are in master which if 4.5 openshift version.

cc @openshift/openshift-team-monitoring

**Comment by mcginne** [comment]
We're actually using v4.3. I think the query is the same, as I found that query in the `adapter-config` ConfigMap.

**Comment by lilic** [comment]
Okay, thanks. We tend to work via bugzillas so please open a bugzilla issue at https://bugzilla.redhat.com/ as this can help us prioritise your request accordingly, thanks!

**Comment by mcginne** [comment]
@lilic thanks, I've raised -> https://bugzilla.redhat.com/show_bug.cgi?id=1812004

**Comment by paulfantom** [comment]
Closing this in favor of opened bugzilla.
/close
