### ISSUE TITLE
etcd monitoring

### ISSUE THREAD

**Issue by brancz** [openshift/cluster-monitoring-operator#7]
In OpenShift 3.10 etcd is a static pod, so we can use the means available to discover it like any other workload through the Kubernetes API.

The difficult thing is to authenticate and authorize against etcd, currently etcd is only accessible via certificate, which only the apiserver has. 

I propose a similar solution as we were going to ship with UT2 of Tectonic. A separate instance of Prometheus entirely dedicated to monitoring etcd. To secure it, etcd authorization is enabled and a certificate is supplied to apiserver that has access to key-space and the etcd-Prometheus with one that does not - still leaving it with access to the `/metrics` endpoint. Additionally in 3.11 we may be able to ship etcd 3.3 which allows segregating this network-wise as well as etcd allows exposing a port purely for exposing metrics.

/cc @smarterclayton @mxinden @elad661 @ironcladlou

**Comment by s-urbaniak** [comment]
This has been implemented, hence closing.
