### ISSUE TITLE
Doesn't techPreviewUserWorkload deploy Garafana?

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [openshift/cluster-monitoring-operator#718]
Hi,
I enabled `techPreviewUserWorkload` and then Prometheus Operator and Prometheus were deployed. But Grafana is not deployed now.
```
$ oc get pod
NAME                                   READY   STATUS    RESTARTS   AGE
prometheus-operator-5476bfc6f5-8nxlg   1/1     Running   0          27h
prometheus-user-workload-0             5/5     Running   1          6h38m
prometheus-user-workload-1             5/5     Running   1          27h
```

Also, I know the Red Hat Support limit which says we cannot modify the monitoring stack Grafana instance.
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/monitoring/cluster-monitoring#maintenance-and-support_configuring-monitoring

So, to monitor user workload on Grafana, I have to deploy our own Grafana right?

regards,
Daiki

**Comment by lilic** [comment]
Hey! Yes this is expected. 

> to monitor user workload on Grafana

We do this because we cannot provide custom dashboards for user metrics if we don't know what the user metrics are, and we like you said do not allow modifying the grafana instance. So yes, you need to provide your own grafana.

**Comment by Daiki-Kawanuma** [comment]
Hi, @lilic 
Thank you for your prompt reply.

I understood it is necessary to provide my own Grafana.
However, I expected "techPrevue User Workload" also deploy Grafana as well as Cluster Monitoring Stack does.

![image](https://user-images.githubusercontent.com/15085341/77324951-d702f180-6d5a-11ea-8417-f315b5f05e13.png)
 
But I guess that Red Hat intend to give us freedom of choice to choose monitoring UI or alert components(Of course, we can also choose Grafana)

regards,
Daiki

**Comment by s-urbaniak** [comment]
@Daiki-Kawanuma user workload monitoring does not deploy grafana on its own, but technically it is possible to connect your own grafana to it.

**Comment by s-urbaniak** [comment]
@Daiki-Kawanuma beware though that connecting to it implies some thought around bearer tokens, as user workload is protected via different proxies, see https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/user-workload-monitoring.md

**Comment by Daiki-Kawanuma** [comment]
Hi, @s-urbaniak 
Thank you for your reply.

According to your link, single Grafana which is deployed by Cluster Monitoring Operator connect to both Cluster Monitoring Stack Prometheus and User Workload Prometheus thorough Thanos Querier.
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/user-monitoring-deployment.png

It's still a Tech Preview feature, but is it supposed to be integrated into a single Grafana in the future?(Will it be possible to change the settings of the Cluster Monitoring Stack Grafana within the support range in the future?)

regards,
Daiki

**Comment by s-urbaniak** [comment]
@Daiki-Kawanuma currently, we do not plan to integrate Grafana into user workload monitoring.

**Comment by Daiki-Kawanuma** [comment]
@s-urbaniak I got it. I'll deploy my own Grafana on my cluster.
Thank you for your kind support!

**Comment by ogre0403** [comment]
@Daiki-Kawanuma Do you have any idea about deploy a separate  Grafana to show user workload?
I found a [reference](https://www.techbeatly.com/2020/03/install-grafana-operator-on-openshift-container-platform-4.html) about create a new Grafana instance. This Grafana can access metrics exposed by Cluster Monitoring Stack, but it can not access user workload.

I though the reason is that the user workload is protected via different proxies as mentioned by @s-urbaniak. Did you have any idea to do this ?

**Comment by chrisob** [comment]
I'm about to invest a few days into researching/implementing Grafana for user workloads, and it'd be great if there was a reference implementation for an application-scoped Grafana.

IMHO app-scoped Grafanas should be able to query user workload metrics as well as cluster-level metrics for user workloads (ie. user app's pod metrics from kube-state-metrics).

CC @s-urbaniak @lilic @brancz :pray:

**Comment by chrisob** [comment]
I think I've come up with an ugly-but-working example of how to deploy an application-scoped Grafana which can make namespace-scoped queries to the Thanos querier: https://github.com/chrisob/openshift-user-workload-monitoring-grafana

RBAC is also restrictive enough that this should work fine for multi-tenant envs (with some minor tweaking).
