### ISSUE TITLE
About application service monitoring

### ISSUE THREAD

**Issue by dongwangdw** [openshift/cluster-monitoring-operator#721]
There is a tech preview for application service monitoring for ocp 4.3. https://docs.openshift.com/container-platform/4.3/monitoring/monitoring-your-own-services.html

After read through it, I did not find any grafana config. I have not put my hands on this. But I want to know if grafana for application monitoring will be the one from cluster monitoring by default or user has to deploy it on their own.

Thanks.

**Comment by lilic** [comment]
Hello,

See discussion in here https://github.com/openshift/cluster-monitoring-operator/issues/718 :)

**Comment by paulfantom** [comment]
Closing as issue is explained and went stale.

/close
