### ISSUE TITLE
Where are the web interfaces exposed?

### ISSUE THREAD

**Issue by andersflemmen** [openshift/cluster-monitoring-operator#76]
I have the operator up and running in minishift after using the ``deploy-on-openshift`` script, but I am having trouble understanding where I can reach the prometheus, alertmanager and grafana dashboards. According to [the docs](https://github.com/openshift/cluster-monitoring-operator/blob/master/Documentation/cluster-monitoring.md#accessing-prometheus-and-alertmanager), they should be available at the $CLUSTER_DNS, but where exactly is this?

**Comment by squat** [comment]
@andersflemmen the easiest way to discover how to access the monitoring services is to run:
```
oc get routes -n openshift-monitoring
```
This will print a list of DNS names you can use to access the various monitoring services, e.g. Prometheus.

**Comment by andersflemmen** [comment]
@squat I see, so it is required to use the Host header and access them through the minishift ip web ports? 

Having problems getting the openshift authentication page to work properly, it either goes to the wrong port, or gives an invalid_request error. I am running a haproxy on the server where minishift is running.
