### ISSUE TITLE
AdditionalScrapeConfigs for user apps

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/cluster-monitoring-operator#764]
I see the workload manager is [being extended to support user apps](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/user-workload-monitoring.md) and this is [now in tech preview](https://docs.openshift.com/container-platform/4.3/monitoring/monitoring-your-own-services.html). Are there any plans to support [AdditionalScrapeConfigs like the prometheus operator does](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md)?

**Comment by cdmikechen** [comment]
Also want to know if there is a similar method.
Now I just need to add similar parameters, Openshift will automatically update the configuration I added back. Where is Openshift configured for automatic rollback? I want to know how to turn off the rollback function

**Comment by paulfantom** [comment]
> Are there any plans to support AdditionalScrapeConfigs like the prometheus operator does?

There are no such plans. If you need such a feature please file an OpenShift RFE ticket: https://access.redhat.com/solutions/73513


> I want to know how to turn off the rollback function

This is not possible as the operator model principle it to converge to a set state. Additional parameters are overwritten on next reconciliation pass (max after 5 minutes).

/close
