### ISSUE TITLE
metric names

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/cluster-monitoring-operator#768]
A couple of the metrics with this prometheus have different names from the names with the prometheus from the standard helm chart (the one at https://kubernetes-charts.storage.googleapis.com). In particular (standard one on left)

kubernetes_namespace  becomes namespace
service becomes exported_service

Is this intentional? Is there a way to configure it?

**Comment by paulfantom** [comment]
Those are custom labels defined by prometheus helm chart. We have no plans on aligning.
For example `kubernetes_namespace` is created here: https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L1334-L1336

You would get the same labels when running prometheus-operator instead.

/close
