### ISSUE TITLE
Thanos querier grpc port

### ISSUE THREAD

**Issue by pablo-ruth** [openshift/cluster-monitoring-operator#772]
Hi!

I'm trying to connect to the thanos querier grpc port from another querier instance outside of the cluster which allows use to federate all our prometheus endpoints. The grpc port seems to listen only on localhost (https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/thanos-querier.jsonnet#L205) and there is no auth proxy configured for it, so is it a way to configure this behavior to expose it ?

Thanks

**Comment by paulfantom** [comment]
There are no plans to expose grpc endpoint of thanos querier. If this is something you need, please submit an RFE for OpenShift.

/close
