### ISSUE TITLE
RFE: allow configuring node-exporter's metrics

### ISSUE THREAD

**Issue by ibotty** [openshift/cluster-monitoring-operator#796]
It would be great to be able to configure node-exporters.  The node-exporter's daemonset always gets reset to default values (as it should).

My use case is temperature monitoring for bare-metal clusters.
Arguably it should also include alerting rules when temperature is rapidly rising/constantly hot.

**Comment by lilic** [comment]
Hello, thanks for your feature request, our RFEs usually go through product manager or customer support, so feel free to contact them and they will prioritise it.

For now, you can deploy node_exporter in user namespaces and configure it, and with user workload monitoring create alerts based on those metrics.

**Comment by paulfantom** [comment]
> Arguably it should also include alerting rules when temperature is rapidly rising/constantly hot.

See upstream node_exporter issue exactly about this https://github.com/prometheus/node_exporter/pull/1681

> My use case is temperature monitoring for bare-metal clusters.

In next releases, when we include node_exporter 1.0, this will be improved with 
`thermal_zone` collector which is enabled by default in recent node_exporter versions.

/close
