### ISSUE TITLE
Improve Contributor experience by adding more information how to contribute to the Readme

### ISSUE THREAD

**Issue by RiRa12621** [openshift/cluster-monitoring-operator#803]
While the Readme and the rest of the documentation explain the underlying concepts as well as the "how to install" very well, as someone who comes in new and willing to contribute, I am missing some "getting started".
The maintainers, especially @lilic have been very nice and helpful as usual but I don't think this scales with more potential contributors coming to the project.
 
The [Kubernetes-Mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) has some basics around `jb` which helped me to get started and could be added here plus some more.
I will try to send a PR once I fully went through the flow but so far what would have helped me greatly are the following
- reference to jsonnet doc
- what tools do I need
- how do I get jsonnet
- how do I get jb
- which commands do I have to run to complement the bare jsonnet changes with generated files
- which commands should I run before sending a PR

**Comment by lilic** [comment]
I would suggest the following, if you can do the following points in https://github.com/coreos/kube-prometheus or/and mixin repo and link in cluster-montioring-operator to those 
> reference to jsonnet doc
what tools do I need
how do I get jsonnet
how do I get jb

As for
> which commands do I have to run to complement the bare jsonnet changes with generated files
which commands should I run before sending a PR

Those sound great!
Thanks again 🎉 :)

**Comment by paulfantom** [comment]
I agree, we don't have the best contributor experience :(

---

For the future:

> what tools do I need
> how do I get jsonnet
> how do I get jb

With https://github.com/openshift/cluster-monitoring-operator/pull/725 those will be handled by `make generate`.

> which commands do I have to run to complement the bare jsonnet changes with generated files
> which commands should I run before sending a PR

Currently `make generate-in-docker`, in the future `make generate`

Additionally you should do `MAKE=make make <target>` on OSX.

**Comment by RiRa12621** [comment]
I wonder if it makes sense to wait with cooking a PR for this until #725 is in then @paulfantom

**Comment by paulfantom** [comment]
Fixes from #725 will affect development cycles from 4.6 (hopefully) onwards. We will probably still need some guide for earlier versions.

I think it is ok to do it now and later we can adjust. Especially that even right now most of the things should be handled OOTB by `make generate-in-docker`.

**Comment by lilic** [comment]
Also the docs I outlined above can be done now in upstream and linked here regardless of the merge of the PR :)

**Comment by RiRa12621** [comment]
Yes I did check the docs on kube-prometheus @lilic and there's some [there](https://github.com/coreos/kube-prometheus#update-from-upstream-project) already. Maybe I'll extend that a bit and then link it here. Seems to be the easiest option
