### ISSUE TITLE
Cluster monitoring operator fails to recreate a missing route

### ISSUE THREAD

**Issue by mic4ael** [openshift/cluster-monitoring-operator#812]
I have been playing with OKD4 for some time. I want to customize the hostnames of the routes managed by the operator. According to what I have found in the code it should be possible to create the following `ConfigMap` and expect the routes to be properly created (provided that I removed the routes before creating the configmap).

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    prometheusK8s:
      hostport: "example.com"
    alertmanagerMain:
      hostport: "example-1.com"
    grafana:
      hostport: "example-2.com"
```
For example, this is a snippet which IMO proves that the operator should create the route with my custom hostname:

```go
r, err := t.factory.GrafanaRoute()
if err != nil {
    return errors.Wrap(err, "initializing Grafana Route failed")
}

err = t.client.CreateRouteIfNotExists(r)
if err != nil {
    return errors.Wrap(err, "creating Grafana Route failed")
}
```

Unfortunately this is not working as it should. The route is not recreated and there is an error from the `Updating configuration sharing` task since this task relies on the presence of all the routes in the `openshift-monitoring` namespace.

**Comment by lilic** [comment]
Hey, thanks for the issue! I believe its because the console needs to know the names of the routes to link to them correctly, but IIRC we expose that info in a configmap so that might be why its failing. Curious what is your need to customize those?

**Comment by mic4ael** [comment]
So, yeah. The route hostnames are shared in the `sharing-config` `ConfigMap` in the `openshift-monitoring` namespace only for the console operator. I don't understand why the `Route` resources are not recreated properly. 

> Curious what is your need to customize those?

It is some requirements that we have ;) I am validating whether it is possible.

**Comment by mic4ael** [comment]
What is even weirder is that `AlertManager.spec.externalUrl` is correctly changed to the hostname I provide in the `config.yml`

**Comment by mic4ael** [comment]
My question is why the operator doesn't recreate the `Route` properly.

**Comment by lilic** [comment]
https://github.com/openshift/cluster-monitoring-operator/blob/8871868530d3c494f61f1f2fd8a9283d7fad66b1/pkg/client/client.go#L222-L230

we create Route, not sure what you mean properly? Like route does not exist?

**Comment by mic4ael** [comment]
Yeah, yeah. I saw this piece of code and that is why I created the issue. I don't understand why the `Route` is not being created at all even though the code shows that the Route should be recreated ;)

**Comment by mic4ael** [comment]
Forgot to mention I am using this commit 784585a6

**Comment by mic4ael** [comment]
Maybe this check is wrong?

```go
if apierrors.IsNotFound(err) {
```

**Comment by lilic** [comment]
That should work correctly, we use that error check elsewhere as well, I suspect just the name of the new route you set in the config is not propagated to that function. Can you check that?

**Comment by mic4ael** [comment]
Sorry, I don't understand what you mean. The `Route` passed to `CreateRouteIfExists` is taken e.g. from `GrafanaRoute`

```go
func (f *Factory) GrafanaRoute() (*routev1.Route, error) {
	r, err := f.NewRoute(MustAssetReader(GrafanaRoute))
	if err != nil {
		return nil, err
	}

	if f.config.GrafanaConfig.Hostport != "" {
		r.Spec.Host = f.config.GrafanaConfig.Hostport
	}
	r.Namespace = f.namespace

	return r, nil
}
```

**Comment by mic4ael** [comment]
The problem is for sure not related to my `cluster-monitoring-config` `ConfigMap`. If I remove the `Route` and the `ConfigMap` the route is not recreated

**Comment by mic4ael** [comment]
Actually, that might be a problem with my config.yml in the end. Since the `Route` is recreated if no custom config is provided.

**Comment by mic4ael** [comment]
This is a bit weird :P If I provide the config `grafana.hostport` with the value equal to the default hostname of the grafana route it also doesn't work..

**Comment by mic4ael** [comment]
At this point I really have no idea what is going on here :P There must be a bug in the code. I tried to create a `Route` with my custom `Host` manually and it works without any issue.

**Comment by lilic** [comment]
If you do `oc get routes` you do not see any of these routes?

**Comment by mic4ael** [comment]
> If you do `oc get routes` you do not see any of these routes?

Nope. So to be clear (let's follow my steps in case I would like to customize grafana's `Route`):

1. Remove the `Route` `grafana`:
```bash
oc delete route/grafana -n openshift-monitoring
```

2. Create a `ConfigMap` holding the configuration:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    grafana:
      hostport: "grafana.my-domain.com"
```

Operator tries to resync a few times but the `Route` is never recreated.

3. Now delete the `ConfigMap`

```bash
oc delete cm/cluster-monitoring-config -n openshift-monitoring
```

Operator resyncs and recreates the `Route` properly.

**Comment by lilic** [comment]
Can you try skipping first step in removing the route?

**Comment by mic4ael** [comment]
I mean, It is not really related to the problem I depicted. However, I tried it before and unfortunately the operator doesn't update an already existing `Route`. To be clear it does update the `Route` struct but it doesn't contact the API (as far as I checked) to persist the changes.

**Comment by mic4ael** [comment]
So I think I have found the problem in the end. The main issue here is that `ClusterRole/cluster-monitoring-operator` doesn't have permission to create `Route` objects with custom hostname (`routes/custom-host` permission). Adding it to the `clusterrole` fixes the problem. I would say it is a bug then? BTW, it is also really strange that this error wasn't logged at all even. It might be the problem with how the `TaskRunner` works, but I am not sure.

**Comment by mic4ael** [comment]
Let me know what you think. This seems to be a bug and I can create a PR fixing it if necessary ;)

**Comment by lilic** [comment]
@mic4ael nice find, a PR to fix this is more than welcome! :)

**Comment by brancz** [comment]
If I'm not mistaken, this configuration field was a left over from CoreOS Tectonic, and it only accidentally ended up in the configuration. We intentionally only create and not update routes so the router automatically picks a name. If I recall correctly the OpenShift 4 stance was if one wants a different route, they have to put redirects in front of it themselves.

**Comment by lilic** [comment]
> (I believe this was a larger architectural decision).

Thanks @brancz was not aware of historical decisions. I can follow up if this is still the case? If yes, we should then remove the option to configure this?

**Comment by mic4ael** [comment]
But then, I guess it is a bit inconsistent to allow configuring it via `cluster-monitoring-config`

**Comment by lilic** [comment]
Yes, hence Frederics comment:
> If I'm not mistaken, this configuration field was a left over from CoreOS Tectonic, and it only accidentally ended up in the configuration.

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
