### ISSUE TITLE
monitoring user services not working with 4.3

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/cluster-monitoring-operator#817]
I've enabled the techPreviewUserWorkload feature in 4.3 by following the [4.3 instructions](https://docs.openshift.com/container-platform/4.3/monitoring/monitoring-your-own-services.html#enabling-monitoring-of-your-own-services_monitoring-your-own-services). It is up as the pods got created and I can access it via the OpenShift UI. I've got a service running and set up ServiceMonitor and PodMonitor. But the metrics are not being scraped. They don't appear in queries via the Prometheus UI.

To test my configuration I've also installed 0.32.0 of the [prometheus operator](https://github.com/coreos/prometheus-operator/tree/master/Documentation) via OperatorHub. When I look at that Prometheus, I **do** see the metrics. I've not customised it at all, it is just scraping the Pod based on the ServiceMonitor and PodMonitor specs. The same ones that I was expecting the User Workload Monitoring feature to use.

I first hit this with a custom service but I can recreate it with the example service from the [prometheus operator's documentation](https://github.com/coreos/prometheus-operator/tree/master/example/user-guides/getting-started) and the [example app from the cluster monitoring docs](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/monitoring/monitoring-your-own-services). When I port-forward to the prometheus-operated service for the 0.32.0 prometheus operator then I see the targets being scraped:
![image](https://user-images.githubusercontent.com/22754674/85028689-4d08d000-b173-11ea-8339-6b05c4a24f38.png)
But none of these appear in the targets for the Cluster Monitoring prometheus and none of their metrics are searchable in it. 

I can't see anything that would explain this in the pod logs for either prometheus or its operator. I am struggling to see [anything else in the docs](https://docs.openshift.com/container-platform/4.3/monitoring/monitoring-your-own-services.html#enabling-monitoring-of-your-own-services_monitoring-your-own-services) that I would need to do in order to enable scraping. I didn't do the user role assignment steps but I'm running as a ClusterAdmin (kubeadmin) so I don't think I need to.

**Comment by simonpasquier** [comment]
> But none of these appear in the targets for the Cluster Monitoring prometheus and none of their metrics are searchable in it.

When user workload monitoring is enabled, it deploys another pair of prometheus servers in the `openshift-user-workload-monitoring` namespace. I suspect that you've checked `prometheus-k8s-*` pods instead of ` prometheus-user-workload-*` pods.

**Comment by ryandawsonuk** [comment]
I am checking targets by going to `Monitoring -> Metrics -> Prometheus UI -> Status -> Targets`. Is that not where I should be looking?

**Comment by simonpasquier** [comment]
No the UI you're accessing is the Prometheus service monitoring the infra (openshift) components. The user workload Prometheus pods aren't exposed via a route so you need to port forward:
```
oc port-forward svc/prometheus-operated 9090
```

**Comment by ryandawsonuk** [comment]
Oh, interesting when I do `kubectl port-forward -n openshift-user-workload-monitoring svc/prometheus-operated 9090:9090` and then look at that prometheus then I do see some targets:

![image](https://user-images.githubusercontent.com/22754674/85038373-67947680-b17e-11ea-97be-463d206381c7.png)

Not sure why it's not scraping though.

**Comment by ryandawsonuk** [comment]
Oh I do have the namespace in my service mesh member roll. One difference is that the other prometheus is in the same namespace. This could be an istio thing. I will try adding openshift-user-workload-monitoring to the member roll.

**Comment by ryandawsonuk** [comment]
Aha, that seems to do the job:

![image](https://user-images.githubusercontent.com/22754674/85039784-fb1a7700-b17f-11ea-89b0-8a0eaf51b883.png)

Thanks!
