### ISSUE TITLE
grafana pod outbound network connections

### ISSUE THREAD

**Issue by kwoodson** [openshift/cluster-monitoring-operator#828]
While deploying the cluster-monitoring-operator inside of Azure Red Hat OpenShift we noticed there were some unexpected outbound connections being made.  Customers desire the ability to lock down all necessary outbound cluster traffic to a minimum set required to run a cluster.

cluster-monitoring-operator version:
```
    - name: RELEASE_VERSION
      value: 4.3.18
```

I have traced these connections back to the grafana pod.  (from our network proxy log)
```
time="2020-06-25T20:42:10Z" level=info msg="10.2.0.7:44476->35.241.23.245:443 (grafana.com): raw"
time="2020-06-25T20:42:10Z" level=info msg="10.2.0.7:33440->151.101.208.133:443 (raw.githubusercontent.com): raw"
```

I was able to track this to a cluster node: 
```
kw-border-8l5ls-worker-eastus2-dpf6k   Ready    worker   2d21h   v1.16.2   10.2.0.7  
```

Then by using the tcpdump utility I was able to determine the pod:
```
18:23:34.669504 IP 10.20.10.7.42220 > 151.101.208.133.https: Flags [R], seq 659795616, win 0, length 0
```
`10.20.10.7` is the ip address of the grafana pod:
```
grafana-bf4fd6967-p88db                        2/2     Running   0          4h3m    10.20.10.7
```

This `raw.githubusercontent.com` is a problem with customers which require higher levels of security.

Could we verify what is actually using this `raw.githubusercontent.com`?

The other outbound connection which is the same pod but is reaching out to `grafana.com`:
```
18:32:04.502760 IP 10.20.10.7.50836 > 245.23.241.35.bc.googleusercontent.com.https
```

This could be related to this following issue:
https://community.grafana.com/t/grafana-process-connects-to-port-443/76

I would expect that grafana would not be attempting outbound connections by default.

Could we determine what this second outbound connection is and disable it?

**Comment by kwoodson** [comment]
This could be an artifact from here:
https://github.com/openshift/grafana/blob/master/conf/defaults.ini#L141-L148

**Comment by paulfantom** [comment]
Could you create a bugzilla ticket for this?

**Comment by kwoodson** [comment]
@paulfantom If you still want a bz I can create one.  Apologies as I was out.  Thanks for https://github.com/openshift/cluster-monitoring-operator/pull/834

**Comment by simonpasquier** [comment]
Given that #834 has merged, I think everything's fine now and no Bugzilla is needed.

**Comment by paulfantom** [comment]
Bugzillas are necessary if this needs to be backported to previous OpenShift versions.
