### ISSUE TITLE
[help]cluster monitoring operator is experiencing 40% errors.

### ISSUE THREAD

**Issue by zhangrui153169** [openshift/cluster-monitoring-operator#842]
prometheus.clustermonitoringoperatorerrors: cluster monitoring operator is experiencing 40% errors.;

what does this warning mean?

**Comment by paulfantom** [comment]
I am not sure, but if you are talking about this alert: https://github.com/openshift/cluster-monitoring-operator/blob/91b6c2073b231770f7829b0ab2b41a876e60569f/assets/prometheus-k8s/rules.yaml#L865-L871 then it means that CMO had experienced a 40% failure rate when applying the new configuration.
