### ISSUE TITLE
node-exporter does not come up on openshift e2e runs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/cluster-monitoring-operator#85]
I switched our prometheus e2e tests to use the cluster monitoring operator and I'm seeing some failures in about 1/4 runs.  The most noticeable is that one run didn't have the node exporter installed (no pods created).

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20830/pull-ci-origin-e2e-gcp/3161/

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/prometheus/prometheus.go:49
Expected
    <[]error | len:1, cap:1>: [
        {
            s: "no match for map[job:node-exporter] with health up and scrape URL ^https://.*/metrics$",
        },
    ]
to be empty
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/prometheus/prometheus.go:123
```

In this run the e2e tests start at 13:37, but the prometheus test isn't run until 13:45, which should be more than enough time for node-exporter to come up.  I see no pods created, which implies either the daemonset wasn't created, or the daemonset failed massively.  I see no events for the daemonset in 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/20830/pull-ci-origin-e2e-gcp/3161/artifacts/e2e-gcp/events.json which implies it didn't get created.

I see the following in the logs for prometheus operator (which seems bad) but nothing in cluster monitoring operator that is excessive.

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/20830/pull-ci-origin-e2e-gcp/3161/artifacts/e2e-gcp/pods/openshift-monitoring_cluster-monitoring-operator-5cf8fccc6-mdc92_cluster-monitoring-operator.log.gz

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/20830/pull-ci-origin-e2e-gcp/3161/artifacts/e2e-gcp/pods/openshift-monitoring_prometheus-operator-6c9fddd47f-mb4br_prometheus-operator.log.gz

```
W0903 14:01:42.210505       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-09-03T14:01:43.178075004Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
W0903 14:01:43.178176       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0903 14:01:43.178307       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0903 14:01:43.196450       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0903 14:01:43.222385       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0903 14:01:43.222448       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-09-03T14:01:43.222295876Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
W0903 14:01:43.240970       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0903 14:02:03.033696       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-09-03T14:02:03.033607297Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
W0903 14:02:03.033767       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0903 14:02:03.048325       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-09-03T14:02:19.767518749Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
W0903 14:02:45.489186       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0903 14:02:45.489268       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-09-03T14:02:45.489057156Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
W0903 14:02:45.504357       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
```

**Comment by smarterclayton** [comment]
@brancz a significant source of flakes in the 3.11 e2es

**Comment by brancz** [comment]
@mxinden those warnings were recently fixed, no? Did we update the Prometheus Operator version?

**Comment by smarterclayton** [comment]
We'd be getting events if we couldn't schedule.

**Comment by brancz** [comment]
Ah I actually found something in the logs of the cluster-monitoring-operator:

```
E0903 13:43:24.094244       1 operator.go:186] Syncing "openshift-monitoring/cluster-monitoring-config" failed                                                                           
E0903 13:43:24.187314       1 operator.go:187] Sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating Alertmanager failed: waiting for Alertmanager object changes failed: timed out waiting for the condition
```

What do the Alertmanager logs say or do the Pods even schedule from its StatefulSet?

**Comment by mxinden** [comment]
For the record `Index with name namespace does not exist` was fixed in https://github.com/coreos/prometheus-operator/pull/1706. Should just be ignored as client-go falls back to simply iterating the given store.

**Comment by smarterclayton** [comment]
I see alertmanager pods here so they get created at some point https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/20830/pull-ci-origin-e2e-gcp/3161/artifacts/e2e-gcp/pods/

**Comment by s-urbaniak** [comment]
@smarterclayton Thanks a lot for the logs and pods traces, this helps tremendously! :+1: 

I think we can narrow it down to the cluster monitoring operator not reaching the point to create the daemonset node exporter at all.

In fact it also doesn't create the kube-state-metrics deployment (both artifacts are missing in the pods overview).

While looking at the operator logic:

https://github.com/openshift/cluster-monitoring-operator/blob/d6d5b11416ebd8bbe615801d43d4bf2e95e35721/pkg/operator/operator.go#L238-L244

I see the following log entries from https://storage.googleapis.com/origin-ci-test/pr-logs/pull/20830/pull-ci-origin-e2e-gcp/3161/artifacts/e2e-gcp/pods/openshift-monitoring_cluster-monitoring-operator-5cf8fccc6-mdc92_cluster-monitoring-operator.log.gz:
```
I0903 13:55:04.687436       1 tasks.go:37] running task Updating Prometheus Operator
...
I0903 13:55:23.094065       1 tasks.go:37] running task Updating Grafana
...
I0903 13:55:30.198715       1 tasks.go:37] running task Updating Prometheus-k8s
...
I0903 14:01:30.888512       1 tasks.go:37] running task Updating Alertmanager
E0903 13:49:12.972447       1 operator.go:186] Syncing "openshift-monitoring/cluster-monitoring-config" failed
E0903 13:49:12.972481       1 operator.go:187] Sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating Alertmanager failed: waiting for Alertmanager object changes failed: timed out waiting for the condition
...
(retries the above a couple of times)
...
I0903 14:01:30.888512       1 tasks.go:37] running task Updating Alertmanager
I0903 14:01:30.888611       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.090741       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.187570       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.287753       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.304566       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.487412       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.490592       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.493077       1 decoder.go:224] decoding stream as YAML
I0903 14:01:32.587637       1 decoder.go:224] decoding stream as YAML
<EOF>
```

This might be a simple flake, where the e2e tests simply gives up "too fast", admittedly it takes a long time (~15 minutes).

@smarterclayton @brancz : are the monitoring (and also alertmanager) images downloaded from the internet or are they cached internally from Openshift?

**Comment by brancz** [comment]
It would be pretty invasive, but possible to parallelize some of these things. Right now the big dependency there is, is that the Prometheus Operator is setup first, then the only remaining dependency is between Prometheus and Grafana as the Grafana task sets up some resources that the Prometheus task depends on.

**Comment by brancz** [comment]
@smarterclayton just to see if our suspicion is correct, would it be possible to increase the timeout to see if it eventually deploys?

**Comment by smarterclayton** [comment]
Which timeout?  If we think this is a GCE PD problem we should copy the
storage team in - I've never noticed this before, but if PVs are lagging
we'd want to know.

**Comment by brancz** [comment]
Yes good point.

**Comment by s-urbaniak** [comment]
@smarterclayton do you have any references to people in the storage team we can ping here? It _seems_ there is not much we can do in the cluster-monitoring-operator itself.

**Comment by smarterclayton** [comment]
@openshift/sig-storage

**Comment by smarterclayton** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1627547

**Comment by s-urbaniak** [comment]
closing this out here, as it does not seem to be related to the cluster monitoring operator.
