### ISSUE TITLE
Make Cluster Monitoring Operator an optional feature

### ISSUE THREAD

**Issue by jomeier** [openshift/cluster-monitoring-operator#874]
Hi,

in the last days we tried to add our OpenShift 4 cluster to a central monitoring solution based on Thanos/Grafana/Prometheus that monitors several OpenShift clusters and is running outside of the cluster.

We added own metrics, prometheus rules and Grafana Dashboards and had to install our own Prometheus operator. Sadly this one collides with the Prometheus operator that is installed by the Cluster Monitoring Operator in the OpenShift cluster we like to monitor.

Our procedure to get this setup running was:
- turn off the Cluster Monitoring Operator (set it to unmanaged state) in the CVO
- delete almost all resources in the openshift-monitoring namespace
- add an NGINX server in openshift-monitoring that reverse proxies the web console traffic to our own monitoring stack that is running in a different namespace (but uses almost the same components) and also terminates TLS traffic to the UI using the proper certs.

This works great. We see all metrics and graphs in the OpenShift console again.

But: If we turn off the Cluster Monitoring Operator the cluster won't be able to upgrade because the CVO doesn't proceed upgrading the cluster if an operator is in unmanaged state.

**Is it possible to prevent the Cluster Monitoring Operator to create resources in the cluster / being an optional feature without hacky workarounds during the cluster installation in a way, that the cluster can be still upgraded ?**

Other k8s distributions allow to disable the cluster monitoring with a switch. We would love to have a similar option, because this gives us more freedom of how we integrate an OpenShift cluster into our environment.

We know that Red Hat is improving the Cluster Monitoring steadily but also give us the freedom to install our own stack, please.

Thanks a lot and greetings,

Josef

**Comment by lilic** [comment]
Hello! Cluster monitoring operator is core component and is needed for various reasons, there are no plans at this time to move it away from being core and installed by default. But you can look into moving away from your custom setup and instead use the new user workload monitoring feature. :)

**Comment by jomeier** [comment]
That‘s not the answer I was hoping for 😀

Do you have any blog posts or best practices for us how we can integrate multiple OpenShift 4 clusters in a Prometheus/Thanos/Grafana based Central Cluster Monitoring?

**Comment by lilic** [comment]
You mean to push metrics/alerts from each cluster to a central openshift cluster to display all the data from all the clusters? 
There is remote write for this, this feature is not fully supported but is one option.

**Comment by vrutkovs** [comment]
> Cluster monitoring operator is core component and is needed for various reasons

Can we have an unsupportedNoUpgradeUseAtYourOwnRisk switch? This might be useful CRC/SingleNodeCluster/developement usecases I suppose

**Comment by lilic** [comment]
> This might be useful CRC/SingleNodeCluster/developement usecases I suppose

There is nothing decided on that, I believe we are waiting from your side on the requirements for that, as well as the CRC team? At least our team has not gotten those yet and because of that, the work is not planned for the next 6 months at least, last time we spoke with PM.

**Comment by jomeier** [comment]
Yes all metrics/alerts should be pushed to a central (OpenShift) cluster.

I would love to get upgrades for all monitoring components (because some of them like PrometheusRules will also be used by custom stacks) but have an 

unsupportedCustomMonitoringClusterMonitoringDeploymentsAreDisabled switch.

**Comment by lilic** [comment]
> Yes all metrics/alerts should be pushed to a central (OpenShift) cluster.

@jomeier this is not be supported, you can push from cluster but not to another OpenShift cluster with the default monitoring setup, this is not in the plans yet that I am aware of. cc @sichvoge @brancz maybe have more details?

**Comment by jomeier** [comment]
@lilic 
And this is one of the reasons why people fiddle around with monitoring and a must have in my opinion.

Because in realitiy you always have more than only one cluster (On Premises, public cloud, several regions, ...).

**Comment by lilic** [comment]
Understand completely, but this is not on the developer teams radar currently but you can request the feature through official channels as well to make sure they know our customers really want this :)

**Comment by jomeier** [comment]
What is the official channel of an open source project :-) ?

The current implementation does not support it, can not be switched off in a clean way. That hurts.

**Comment by brancz** [comment]
It's an explicit product and architectural decision to always have monitoring, and not to make it optional in any way. If you want to remove it you must put the product in an unsupported, unupgradable state. Monitoring is required.

It's dev preview, but you can remote-write metrics to a remote storage with the cluster monitoring configuration.

**Comment by lilic** [comment]
> The current implementation does not support it, can not be switched off in a clean way. That hurts.

@jomeier CVO is the one that installs cluster monitoring operator, we just create the manifests. :) If you want to make it optional this needs to be done in another moving part. But as we said currently monitoring is required component and there is no change into that on the radar.

**Comment by s-urbaniak** [comment]
Closing out due to staleness.
