### ISSUE TITLE
serviceMonitor in namespace

### ISSUE THREAD

**Issue by vincent-pli** [openshift/cluster-monitoring-operator#890]
I saw in [READM.md](https://github.com/openshift/cluster-monitoring-operator), it said:
```
Important: The Prometheus Operator managed by the Cluster Monitoring Operator will by default only look for ServiceMonitor resources in openshift-monitoring namespace.
```
Actually, it's not, seems it looks in `namespace` labeled with `openshift.io/cluster-monitoring=true`, and inject the matched `namespace`s as parameter: `--namespaces` to deployment of `prometheus operator`.

BTW, we set the cr: `Prometheus`'s field:
```
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
```
people know that's means no filter on `namespace` and `serviceMonitor`, but actually wrong, we hide the implements, that will confuse people, do we mentioned it in documents, thanks.

**Comment by lilic** [comment]
@vincent-pli  Hey thanks for your issue to clarify, you mean we should correct the readme to not be misleading?

**Comment by vincent-pli** [comment]
@lilic 
Yeah, at least not misleading people.
