### ISSUE TITLE
how to scale down alertmanager and prometheus?

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/cluster-monitoring-operator#896]
I have seen this discussed in https://github.com/openshift/cluster-monitoring-operator/issues/309
But for an edge case I would still like to scale down alertmanager and prometheus to only 1 instance each.
I have tried to edit the alertmanager object "main" and the prometheus object "k8s" and when I change the .spec.replicas to 1 this is performed but reset only a couple of minutes later.
Where do I have to make a change to get this persistent?
In https://github.com/openshift/cluster-monitoring-operator/blob/master/Documentation/user-guides/configuring-cluster-monitoring.md
I do not see options for this. :-(

**Comment by paulfantom** [comment]
> But for an edge case I would still like to scale down alertmanager and prometheus to only 1 instance each.

This is not supported. If you need such a feature please create an RFE for OpenShift following RFE process https://access.redhat.com/solutions/73513
