### ISSUE TITLE
using thanos for querying?

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/cluster-monitoring-operator#911]
I'm currently querying against the prometheus of the cluster monitoring operator, hitting the [prometheus-k8s service](https://github.com/openshift/cluster-monitoring-operator/issues/790#issuecomment-630171976). That works fine. Now I've a situation where my queries could easily exceed the [11,000 data point max resolution](https://github.com/prometheus/prometheus/issues/2253) on prometheus. I'm guessing that limit applies for the cluster monitoring operator's prometheus too. So I'm wondering about Thanos. I see there's references to Thanos in [this codebase](https://github.com/openshift/cluster-monitoring-operator/search?q=thanos&unscoped_q=thanos). Is Thanos automatically installed with the operator and is there a Thanos query API available for me to query? Or is Thanos something that I would have to install separately?

**Comment by simonpasquier** [comment]
You can use the Thanos querier [service](https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/thanos-querier/service.yaml) but you'll hit the same [limit](https://github.com/thanos-io/thanos/blob/04a7f546e3e99f9bd26a0dba8945b10f272d87ff/pkg/api/query/v1.go#L330-L335). If you're returning that many datapoints, you have to split the query in smaller intervals from client-side.

**Comment by ryandawsonuk** [comment]
Probably I've not explained my aim well or maybe I've misunderstood what the downsampling feature in Thanos does.

I want to query kube-state-metrics pod data over a time range of about a month with intervals of days or weeks. Each interval would have more than 11,000 data points if the raw prometheus data were used. But I'm thinking that with Thanos I could have access to [downsampled data](https://github.com/thanos-io/thanos/issues/813). I believe Thanos would be automatically deriving alternative time series data with a resolution which is as though the scrapes had taken place at 5m and 1hr intervals. For my case if I could use the 1hr-resolution downsampled data my queries should be fine. I believe the concept of auto-downsampling means it [automatically chooses](https://github.com/thanos-io/thanos/issues/1316#issuecomment-509971346) between raw, 5m or 1hr resolutions.

So I'm hoping I can keep the interval but change which sample resolution the query is run against. Apologies for not explaining that. Please do let me know if there's anything I might be misunderstanding or here or any red flags for doing this cluster monitoring (e.g. cluster monitoring retention periods might be different or configuring them might be different).

**Comment by s-urbaniak** [comment]
@ryandawsonuk downsampling is part of Thanos Compactor which is not deployed in the in-cluster monitoring stack. We only deploy Thanos Querier, Thanos Sidecar, and Thanos Ruler (for user workload monitoring).

**Comment by ryandawsonuk** [comment]
Thanks for letting me know @s-urbaniak . I think that answers my key question.
