### ISSUE TITLE
Feature Request: Upload snapshot to s3

### ISSUE THREAD

**Issue by ibotty** [openshift/cluster-monitoring-operator#946]
For backup purposes it would be great to upload prometheus snapshots to s3.  The thanos sidecar can do that automatically.

**Comment by cryptobioz** [comment]
This feature is essential, not only for backup purpose but also to enable the long-term storage of the Prometheus metrics.

**Comment by lilic** [comment]
Hey 👋 Best would be to request this feature via OpenShift customer support so it gets to our product manager :)

**Comment by Cyben** [comment]
Any updates on that feature? Couldn't find any documentation about that.

**Comment by debMan** [comment]
> /close

So, why?
