### ISSUE TITLE
Issue in federation using additionalScrapeConfigs

### ISSUE THREAD

**Issue by ppnaik1890** [openshift/cluster-monitoring-operator#991]
We have two openshift clusters both having prometheus. I want to federate data from prometheus on one cluster to the other. 
We followed the following steps to add the federation job in the prometheus operator CRD:
[https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md)

However, we observe that the changes done to the CRD are reverted in few seconds. Looks like the cluster monitoring operator reverts these changes. Is there a way we can disable this.
My openshift version is 4.4.6.
Thanks!

**Comment by simonpasquier** [comment]
:wave: this isn't supported for now. As stated in the [docs](https://docs.okd.io/latest/monitoring/configuring-the-monitoring-stack.html#support-considerations_configuring-the-monitoring-stack), it's not possible to customize the monitoring components outside of what CMO allows.
